stages:
  prepare:
    cmd: python starter/prep_data.py
    deps:
      - data/census.csv
      - starter/ml
      - starter/prep_data.py
    outs:
      - data/train/X.csv
      - data/train/y.csv
      - data/test/X.csv
      - data/test/y.csv
      - data/preprocessors/encoder.pkl
      - data/preprocessors/lb.pkl
      - data/preprocessors/scaler.pkl
  train:
    cmd: python starter/train_model.py
    deps:
      - data/train/X.csv
      - data/train/y.csv
    params:
      - tuning
      - gridsearch
      - model
    outs:
      - model/${model}.pkl
  evaluate:
    cmd: python starter/eval_model.py
    deps:
      - model/${model}.pkl
      - data/test/X.csv
      - data/test/y.csv
    params:
      - model
    metrics:
      - model/eval.json:
          cache: false