tuning:
  n_estimators: 
    - 50
    - 100
    - 150
    - 200
  max_features:
    - sqrt
    - log2
    - 0.99
    - 0.75
  criterion:
    - gini
    - entropy
    - log_loss
  class_weight:
    - balanced
  
gridsearch: true

model: RandomForestClassifier