tuning:
  n_estimators: 
    - 50
    - 100
    - 150
  max_features:
    - sqrt
    - log2
    - 0.75
  class_weight:
    - balanced
  max_depth:
    - 10
    - 20
  
gridsearch: true

model: RandomForestClassifier