name: Build-and-Deploy-to-Render

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:      
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-code
      uses: actions/checkout@v3 
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: setup DVC
      uses: iterative/setup-dvc@v1
    - name: DVC pull
      run: |
        dvc pull -r s3
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest
    - name: Setup Fly.io
      uses: superfly/flyctl-actions/setup-flyctl@master
    - name: Deploy to Fly.io
      run: flyctl deploy --remote-only
