name: Build-and-Deploy-to-Render

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-code
      uses: actions/checkout@v2 
    # - name: Authenticate to Google Cloud
    #   uses: google-github-actions/auth@v1.1.1
    #   with:
    #     credentials_json: ${{ secrets.GDRIVE_CREDS }}
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: setup DVC
      uses: iterative/setup-dvc@v1
      env: 
        GDRIVE_CREDENTIALS_DATA: '${{ secrets.GDRIVE_CREDS }}'
    - name: DVC pull
      run: |
        dvc pull -r drive
      env: 
        GDRIVE_CREDENTIALS_DATA: '${{ secrets.GDRIVE_CREDS }}'
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest
