name: Build-and-Deploy-to-Render

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout-code
      uses: actions/checkout@v2 
#     - name: Authenticate to Google Cloud
#       uses: google-github-actions/auth@v1.1.1
#       with:
#         credentials_json: ${{ secrets.GDRIVE_CREDS }}
    - name: Set up Python 3.10.12
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install dependencies.
      run: |
        python -m pip install --upgrade pip
        pip install pytest flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi 
    - name: Update DVC Creds and pull
      run: |
        echo "${{ secrets.GDRIVE_CREDS }}" > ./secrets.json
        dvc remote modify drive \
                    gdrive_service_account_json_file_path \
                    ./secrets.json
        dvc pull
        rm -rf secrets.json
    - name: Lint with flake8
      run: |
        flake8 .
    - name: Test with pytest
      run: |
        pytest
